name: "Label Check"

on:
  pull_request:
    types: [labeled, unlabeled, synchronize]
  workflow_run:
    workflows: ["Auto Label PR"]
    types:
      - completed

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check for labels
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: bug,documentation,duplicate,enhancement,help wanted,good first issue,invalid,question,wontfix,breaking-change,dependencies,chore
          repo_token: ${{ secrets.GITHUB_TOKEN }}
